rubble_params:
  pre_allocated_files_num: 100
  pre_allocated_files_size: 64  # in MB
  rocksdb_version: '123'
  replicator_version: '123'
  num_chan: 8
  replica_num: 2  # Number of replicas(length of chain). Currently this number is equal to server number.
  shard_num: 1
  shard_ports:
    shard-0:
      - 0.0.0.0:50051 
      - 0.0.0.0:50051 
    # shard-1:
    #   - 10.10.1.2:50051
    #   - 10.10.1.1:50052
  batch_size: 1000



