rubble_params:
  pre_allocated_files_num: 100
  pre_allocated_files_size: 64  # in MB
  rocksdb_version: '123'
  replicator_version: '123'
  replicator_ip : 0.0.0.0
  replicator_port: 50050
  num_chan: 8
  replica_num: 2  # Number of replicas(length of chain). Currently this number is equal to server number.
  shard_num: 1
  shard_info:
    - tag: shard-0  # Tag of the shard.
      sequence:
        - ip: 0.0.0.0 # IP for the rubble client on each machine, following the sequence of chain(head->...->tail).
          port: 50051
        - ip: 128.110.154.9
          port: 50051
    # - tag: shard-1
    #   sequence:
    #     - ip: 128.110.153.93
    #       port: 50051
    #     - ip: 128.110.153.93
    #       port: 50052
  batch_size: 1000
  # ycsb_workload: a


