rubble_params:
  pre_allocated_files_num: 100
  pre_allocated_files_size: 64  # in MB
  rocksdb_version: '123'
  replicator_version: '123'
  chan_num: 16
  replica_num: 2  # Number of replicas(length of chain).
  shard_num: 2
  shard_ports:
    shard-0:
      - 128.110.153.157:50051
      - 128.110.153.157:50052
    shard-1:
      - 128.110.153.197:50051
      - 128.110.153.197:50052
  batch_size: 500
