rubble_params:
  pre_allocated_files_num: 100
  pre_allocated_files_size: 64  # in MB
  rocksdb_version: '123'
  replicator_version: '123'
  replica_num: 2  # Number of replicas(length of chain). Currently this number is equal to server number.
  shard_num: 2
  shard_ports:
    shard-0:
      - 10.10.1.1:50051
      - 10.10.1.2:50052
    shard-1:
      - 10.10.1.2:50051
      - 10.10.1.1:50052
  batch_size: 5
